### ISSUE TITLE
File exists error

### ISSUE THREAD

**Issue by dlewand691** [vecta-io/nanosvg#3]
Following the CLI instructions I `cd` into my folder where my SVGs are saved. Running the command is giving me this error:

```
➜  Logos nanosvg *.svg ./compressed/ --key HIDDEN --mode 1 
Compressed: logo-cog-cdb-aiAnalytics-vertical-white.svg  10.3KB -> 4.6KB 55.22% saved
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EEXIST: file already exists, mkdir '/Users/ctsuser1/Desktop/Cognizant/__ COG BRANDING/Logos/logo-cog-cdb-aiAnalytics-vertical.svg'
Emitted 'error' event at:
    at Pumpify.onerror (/Users/ctsuser1/.npm-packages/lib/node_modules/nanosvg/node_modules/readable-stream/lib/_stream_readable.js:640:52)
    at Pumpify.emit (events.js:182:13)
    at Pumpify.Duplexify._destroy (/Users/ctsuser1/.npm-packages/lib/node_modules/nanosvg/node_modules/duplexify/index.js:191:15)
    at /Users/ctsuser1/.npm-packages/lib/node_modules/nanosvg/node_modules/duplexify/index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
If I create the "compressed" folder myself, the assets aren't created either. Also ran with `sudo` and getting the same error.

**Comment by neel-radica** [comment]
Hi @dlewand691 , I can't seem to replicate the error. Is it ok if you could provide more information (provide some sample files)

**Comment by dlewand691** [comment]
Sure. This is one of the 53 files I'm trying to run thru the CLI. 


[logo-cog-cdb-aiAnalytics-vertical.svg.zip](https://github.com/vecta-io/nanosvg/files/3192385/logo-cog-cdb-aiAnalytics-vertical.svg.zip)

**Comment by neel-radica** [comment]
Hi, I still can't replicate. Are you working on a Mac?

**Comment by dlewand691** [comment]
Yep, on a Macbook Pro. Node -v 10.10.0, npm -v 6.9.0

**Comment by dlewand691** [comment]
Seems that there's something wrong with one of my files. I tried testing just a single one and it processed properly. 

A recommended feature, in this case, would be to throw a detailed error on which file caused the problem. I did get errors in the web interface, could that same logic be used?

**Comment by neel-radica** [comment]
Hi, sure we will look into this issue as soon as possible and let you know once we improved it. Just in case, could you share the svg file you were having problem with?

**Comment by neel-radica** [comment]
Hi @dlewand691 since cli behaves differently in Mac, all you have to do is just wrap the input in double quotes such as shown below: 
`nanosvg "*.svg" ./compressed/ --key KEY  --mode 1`

**Comment by dlewand691** [comment]
Bingo! That worked perfectly adding the quotes. Thank you for the fix! Might want to update the docs to include that, otherwise others will have the same issue.

**Comment by neel-radica** [comment]
Thanks @dlewand691 for bringing it up. The documentation is updated as well. Pls do let us know if there is any other issue or feedback you would like to get across
